### ISSUE TITLE
Traceback 

### ISSUE THREAD

**Issue by fabaff** [esecuritylab/kostebek#5]
This traceback should be properly handled. 

```bash
$ python3 kostebek.py -t Google
[...]
Traceback (most recent call last):
  File "kostebek.py", line 318, in <module>
    core.getTrademarks()
  File "kostebek.py", line 291, in getTrademarks
    fh = open(file)
FileNotFoundError: [Errno 2] No such file or directory: 'results/Google/unique_trademarks.txt'
```

**Comment by esecuritylab** [comment]
Fix v1.1.0
